import React from 'react';
import Navigation from './Navigation'
import AOS from 'aos';
import 'aos/dist/aos.css'; 
import 'animate.css/animate.css';

AOS.init()



const Home = () => {
    return (
        <div>
            <Navigation />
            <main>
                <h1 className="home-animate-1">Commodo culpa eu laborum amet ea officia nisi eiusmod ut duis.</h1>
                <p className="home-animate-2">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?</p>
                <h1 data-aos="fade-up">Commodo culpa eu laborum amet ea officia nisi eiusmod ut duis.</h1>
                <p data-aos="fade-up">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?</p>
                <h1 data-aos="fade-up">Commodo culpa eu laborum amet ea officia nisi eiusmod ut duis.</h1>
                <p data-aos="fade-up">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?</p>
                <h1 data-aos="fade-up">Commodo culpa eu laborum amet ea officia nisi eiusmod ut duis.</h1>
                <p data-aos="fade-up">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi fuga dolor ullam sint quis veniam vel suscipit, autem modi, animi a laboriosam laudantium sed tenetur repellendus, sit explicabo quos pariatur?</p>               
            </main>
        </div>
    );
};

export default Home;